version: '3.8'
name: "hwk-lab"
services:
  terraform:
    image: hashicorp/terraform:latest  # Replace 'latest' with the specific version if needed
    user: "${UID}:${GID}"
    volumes:
      - ~/.tracecat/lab:/home/terraform
    working_dir: /home/terraform
    tty: true
    environment:
      # TODO: Replace with isolated credentials in files
      # and pass into Docker via Docker swarm
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
